# Generated by Django 5.0.2 on 2024-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان سوال')),
                ('question', models.TextField(verbose_name='متن سوال')),
            ],
            options={
                'verbose_name': 'اضافه کردن سوال',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
