# Generated by Django 5.0.2 on 2024-10-06 11:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فارسی دسته بندی')),
                ('en_name', models.CharField(max_length=200, verbose_name='نام انگلیسی دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی جدید',
                'verbose_name_plural': 'اضافه کردن دسته بندی مقالات',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('slug', models.CharField(blank=True, max_length=300, null=True, verbose_name='اسلاگ')),
                ('date', models.CharField(default='15 مهر', max_length=100, verbose_name='تاریخ')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر مقاله')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('writer', models.CharField(max_length=100, verbose_name='نام نویسنده')),
                ('title_seo', models.CharField(max_length=500, verbose_name='عنوان برای سئو')),
                ('meta_seo', models.TextField(verbose_name='توضیحات متا برای سئو')),
                ('keywords', models.CharField(max_length=500, verbose_name='کلیدواژه ها را برای سئو وارد کنید (  با علامت , جدا کنید  )')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weblog.blog_category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
