# Generated by Django 5.0.2 on 2024-10-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام انگلیسی'),
        ),
    ]
