# Generated by Django 5.0.2 on 2024-10-06 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weblog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weblog_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='1403/07/15', max_length=100, verbose_name='تاریخ')),
                ('comment', models.TextField(verbose_name='دیدگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('weblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه های مقالات',
            },
        ),
    ]
