# Generated by Django 5.0.2 on 2024-10-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_weblog_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog_comments',
            name='date',
            field=models.CharField(default='1403/07/21', max_length=100, verbose_name='تاریخ'),
        ),
    ]
