# Generated by Django 5.0.2 on 2024-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='لوگو سایت')),
                ('email', models.CharField(max_length=500, verbose_name='ایمیل')),
                ('phone_ceo', models.CharField(max_length=500, verbose_name='تلفن مدیر ( برای دریافت پیامک ثبت سفارش )')),
                ('phone_contact', models.CharField(max_length=500, verbose_name='شماره تلفن ( برای نمایش در سایت )')),
                ('phone_huge', models.CharField(max_length=500, verbose_name='شماره ثابت ( برای نمایش در سایت )')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='توضیحات درباره ما')),
                ('location', models.TextField(verbose_name='لینک لوکیشن')),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک اینستاگرام')),
                ('youtube', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک یوتیوب')),
                ('telegram', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک تلگرام')),
                ('twitter', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک توییتر')),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک فیسبوک')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
    ]
