# Generated by Django 5.0.2 on 2024-10-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_data',
            old_name='phone_huge',
            new_name='landline_phone',
        ),
    ]
