# Generated by Django 5.0.2 on 2024-10-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0002_rename_phone_huge_site_data_landline_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_data',
            name='working_hours',
            field=models.CharField(default=1, max_length=500, verbose_name='ساعت کاری'),
            preserve_default=False,
        ),
    ]
