# Generated by Django 5.0.2 on 2024-10-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان اطلاعیه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(default='1403/07/21', verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اطلاعیه جدید',
                'verbose_name_plural': 'اضافه کردن اطلاعیه',
            },
        ),
    ]
