# Generated by Django 5.0.2 on 2024-10-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'اطلاعیه جدید', 'verbose_name_plural': 'ارسال کردن اطلاعیه'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.CharField(default='1403/07/21', max_length=1000, verbose_name='تاریخ ایجاد'),
        ),
    ]
