# Generated by Django 5.0.2 on 2024-10-12 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_notice_options_alter_notice_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='تهران', max_length=1000, verbose_name='شهر')),
                ('area', models.CharField(max_length=1000, verbose_name='منطقه')),
                ('address', models.TextField(verbose_name='ادرس')),
                ('location', models.TextField(verbose_name='لوکیشن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ادرس کاربران',
                'verbose_name_plural': 'ادرس',
            },
        ),
    ]
