# Generated by Django 5.0.2 on 2024-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_address',
            options={'verbose_name': 'ادرس', 'verbose_name_plural': 'ادرس کاربران'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.CharField(default='1403/07/24', max_length=1000, verbose_name='تاریخ ایجاد'),
        ),
    ]
