# Generated by Django 5.0.2 on 2024-10-16 22:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن درباره ما'),
        ),
    ]
