# Generated by Django 5.0.2 on 2024-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام دسته بندی')),
                ('english_name', models.CharField(max_length=1000, verbose_name='نام دسته بندی ( انگلیسی )')),
            ],
            options={
                'verbose_name': 'دسته بندی جدید',
                'verbose_name_plural': 'اضافه کردن دسته بندی',
            },
        ),
    ]
