# Generated by Django 5.0.2 on 2024-10-08 18:17

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام محصول')),
                ('english_name', models.CharField(max_length=1000, verbose_name='نام محصول ( انگلیسی )')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='درباره محصول')),
                ('price', models.CharField(max_length=1000, verbose_name='قیمت نهایی محصول')),
                ('off_price', models.CharField(blank=True, max_length=1000, null=True, verbose_name='قیمت تخفیف خورده ( اختیاری )')),
                ('image', models.ImageField(upload_to='product_image', verbose_name='تصویر شاخص محصول')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول جدید',
                'verbose_name_plural': 'اضافه کردن محصول',
            },
        ),
    ]
