# Generated by Django 5.0.2 on 2024-10-08 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_buy_product_keywords_product_meta_seo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=1000, verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی جدید',
                'verbose_name_plural': 'اضافه کردن ویژگی محصول',
            },
        ),
    ]
