# Generated by Django 5.0.2 on 2024-10-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.CharField(default='1403/07/21', max_length=1000, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس فیش واریزی'),
        ),
    ]
