# Generated by Django 5.0.2 on 2024-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.CharField(default='1403/07/24', max_length=1000, verbose_name='تاریخ ایجاد'),
        ),
    ]
