# Generated by Django 5.0.2 on 2024-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='تصویر یا ایکون برای نمایش در صغحه اصلی'),
            preserve_default=False,
        ),
    ]
