# Generated by Django 5.0.2 on 2024-10-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=1, verbose_name='درصد تخفیف'),
            preserve_default=False,
        ),
    ]
