# Generated by Django 5.0.2 on 2024-10-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.CreateModel(
            name='Amazing_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='products.product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'اضافه کردن تخفیف ',
                'verbose_name_plural': 'پیشنهاد شگفت انگیز',
            },
        ),
    ]
