# Generated by Django 5.0.2 on 2024-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.CharField(default='1403/07/27', max_length=1000, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='قیمت تخفیف خورده '),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت نهایی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ranking_AVG',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, editable=False, max_digits=20, null=True, verbose_name='رنکینگ محصول'),
        ),
    ]
