# Generated by Django 5.0.2 on 2024-10-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_cart_created_at_alter_product_off_price_and_more'),
        ('user_account', '0008_alter_notice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.user_address', verbose_name='ادرس'),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='شماره تماس'),
        ),
    ]
