# Generated by Django 5.0.2 on 2024-10-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_cart_address_cart_name_cart_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_payment',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ کل'),
        ),
    ]
